(* Allow for zero or more assignment statements in a single file *)
program = { assignment_statement };

(* A full assignment statement. E.g., "x = 6;" *)
assignment_statement = lhs, assignment_op, rhs, statement_separator;

(* Right-hand side of the assignment *)
rhs = integer | variable_name | arithmetic_statement;

(* Left-hand side of the assignment *)
lhs = variable_name;

(*
An arithmetic statement.

Supports the following:
1 - 1
x + 2
x * y
z / 0
*)
arithmetic_statement =
    (integer | variable_name),
    { arithmetic_operator, (integer | variable_name) };

(* An all-uppercase or all-lowercase variable name *)
variable_name = all_upper_name | all_lower_name;

(* An all-upprcase variable name *)
all_upper_name = up_alpha, { up_alpha };

(* An all-lowercase variable name *)
all_lower_name = low_alpha, { low_alpha };

(* Uppercase alphabet, for use in variable names *)
up_alpha = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I"
    | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T"
    | "U" | "V" | "W" | "X" | "Y" | "Z";

(* Lowercase alphabet, for use in variable names *)
low_alpha = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i"
    | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t"
    | "u" | "v" | "w" | "x" | "y" | "z";

(* Defines an optionally signed integer of one or more digits *)
integer = [ sign ] , digit , { digit };

(* Digits from 0-9 *)
digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9";

(* Defines the signs for a number *)
sign = "+" | "-";

(* Statement separator *)
statement_separator = { whitespace }, ";", { whitespace };

(* Operators *)
arithmetic_operator = plus_op | minus_op | divide_op | multiply_op;
plus_op = { whitespace }, "+", { whitespace };
minus_op = { whitespace }, "-", { whitespace };
divide_op = { whitespace }, "/", { whitespace };
multiply_op = { whitespace }, "*", { whitespace };
assignment_op = { whitespace }, "=", { whitespace };

(* Whitespace *)
whitespace = " " | "\t" | "\n";
