project-meta:
  project-name: E-Calc
  date-started: 2026-03-16
  last-updated: 2026-03-19 # TODO -> update
  languages:
    - Extended Backus-Naur Form (ISO standard)
  status: Experimental
  license: MIT
  version: 0.0.6

build:
  dev-environments:
    - Ubuntu (WSL2)
  no-build: true

team:
  author: Ethan Kletschke
  contributors:
    - name: Ethan Kletschke
      role: Author and owner
      github-username: ethanKletschke
